name: FusionMamba
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://mirrors.pku.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.pku.edu.cn/anaconda/pkgs/main/
  - https://mirrors.pku.edu.cn/anaconda/pkgs/free/
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2025.12.2
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.19
  - pthread-stubs=0.3
  - python=3.8.20
  - readline=8.3
  - setuptools=75.1.0
  - sqlite=3.51.1
  - tk=8.6.15
  - wheel=0.44.0
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - causal-conv1d==1.0.0
      - certifi==2026.1.4
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - cloudpickle==3.1.2
      - cmake==4.2.1
      - contourpy==1.1.1
      - cryptography==46.0.5
      - cycler==0.12.1
      - einops==0.8.1
      - exceptiongroup==1.3.1
      - filelock==3.16.1
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - google-auth==2.48.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - h5py==3.11.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.2
      - idna==3.11
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iniconfig==2.1.0
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lit==18.1.8
      - mamba-ssm==1.0.1
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - medpy==0.5.2
      - networkx==3.1
      - ninja==1.13.0
      - numpy==1.24.4
      - oauthlib==3.3.1
      - opencv-python==4.13.0.92
      - packaging==26.0
      - pillow==10.4.0
      - pip==25.0.1
      - pluggy==1.5.0
      - protobuf==5.29.6
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pyparsing==3.1.4
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - pywavelets==1.4.1
      - pyyaml==6.0.3
      - regex==2024.11.6
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - simpleitk==2.3.1
      - six==1.17.0
      - submitit==1.5.4
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==2.4.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==1.0.25
      - tokenizers==0.20.3
      - tomli==2.4.0
      - torch==1.13.0+cu117
      - torchaudio==0.13.0+cu117
      - torchvision==0.14.0+cu117
      - tqdm==4.67.3
      - transformers==4.46.3
      - triton==2.0.0
      - typing-extensions==4.13.2
      - urllib3==2.2.3
      - werkzeug==3.0.6
      - yacs==0.1.8
      - zipp==3.20.2
prefix: /root/miniconda3/envs/FusionMamba
